name: yqcommon
description: A new Flutter project.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.19.1 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  #  plugin_platform_interface: ^2.1.4
  oktoast: ^3.4.0
  flutter_easyloading: ^3.0.5
  permission_handler: ^11.1.0
  #  路径管理
  path_provider: ^2.1.1
  image_picker: ^0.8.5+3
  #  图片剪辑
  image_cropper: ^5.0.1
  #  图片压缩
  flutter_luban: ^0.1.13
  #  十进制数计算
  decimal: ^2.3.3
  #  数据存储
  shared_preferences: ^2.2.2
  synchronized: ^3.1.0
  #  本地化语言，日期格式化，数字格式化等
  intl: ^0.18.1
  # 处理键盘事件 https://github.com/diegoveloper/flutter_keyboard_actions
  keyboard_actions: ^4.2.0
  # 启动URL的插件（支持Web） https://pub.flutter-io.cn/packages/url_launcher
  url_launcher: ^6.2.1
  #  日期地址选择
  flutter_picker: ^2.1.0
  audioplayers: ^5.2.1
  cached_network_image: ^3.3.0
  flutter_tts: ^3.8.5
  ota_update: ^6.0.0
  # WebView插件 https://github.com/flutter/plugins/tree/master/packages/webview_flutter
  webview_flutter: ^4.4.2
  flutter_svg: ^2.0.9
#  svgaplayer_flutter: ^2.2.0
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' specifies the class (in Java, Kotlin, Swift, Objective-C, etc.)
  # which should be registered in the plugin registry. This is required for
  # using method channels.
  # The Android 'package' specifies package in which the registered class is.
  # This is required for using method channels on Android.
  # The 'ffiPlugin' specifies that native code should be built and bundled.
  # This is required for using `dart:ffi`.
  # All these are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.yuanquan.yqcommon
        pluginClass: YqcommonPlugin
      ios:
        pluginClass: YqcommonPlugin
  #      web:
  #        pluginClass: YqcommonWeb
  #        fileName: yqcommon_web.dart

  # To add assets to your plugin package, add an assets section, like this:

  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
#
#fluwx:
#  app_id: 123456
#  # only debug in debug mode
#  debug_logging: true
#  android:
#  #    interrupt_wx_request: true # default is true
#  #    flutter_activity: MainActivity #Default to launch app's launcher
#  ios:
#    universal_link: https://testdomain.com
#    scene_delegate: true #default false
## payment is enabled by default
##    no_pay: true